apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
      rolearn: arn:aws:iam::471112597139:role/eks-node-role
  mapUsers: |
    - userarn: arn:aws:iam::471112597139:user/hanaldo
      username: hanaldo
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system